version: "3"
services:
  node:
    container_name: sts
    image: "node:9"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - /var/docker/sts/mount/sts-deckbuilder:/home/node/app
    expose:
      - "3000"
    command: "npm start"
    restart: unless-stopped
    network_mode: "host"
    labels:
              - "traefik.backend=sts"
              - "traefik.frontend.rule=Host:sts.robinlebert.fr"
              - "traefik.enable=true"
              - "traefik.port=3000"
networks:
  default:
    external:
      name: local
